name: WordPress Theme Quality Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  phpcs-check:
    name: PHP Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction
    
    - name: Run PHPCS
      run: |
        if [ -f "./vendor/bin/phpcs" ]; then
          ./vendor/bin/phpcs --standard=phpcs.xml --report=summary || true
        else
          echo "PHPCS not found, skipping..."
        fi
    
    - name: Check PHP syntax
      run: |
        echo "🔍 Checking PHP syntax..."
        syntax_errors=0
        for file in $(find . -name "*.php" -not -path "./vendor/*"); do
          if ! php -l "$file" > /dev/null 2>&1; then
            echo "❌ Syntax error in: $file"
            php -l "$file"
            syntax_errors=$((syntax_errors + 1))
          else
            echo "✅ $file - OK"
          fi
        done
        
        if [ $syntax_errors -gt 0 ]; then
          echo "❌ Found $syntax_errors syntax errors"
          exit 1
        else
          echo "✅ All PHP files have valid syntax!"
        fi

  basic-tests:
    name: Basic Theme Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Verify theme files
      run: |
        echo "🔍 Checking required theme files..."
        [ -f "style.css" ] && echo "✅ style.css found" || echo "❌ style.css missing"
        [ -f "functions.php" ] && echo "✅ functions.php found" || echo "❌ functions.php missing"
        [ -f "index.php" ] && echo "✅ index.php found" || echo "❌ index.php missing"
        
        echo "📊 Theme structure:"
        find . -name "*.php" -not -path "./vendor/*" | wc -l | xargs echo "PHP files:"
        find . -name "*.css" -not -path "./vendor/*" | wc -l | xargs echo "CSS files:"
        find . -name "*.js" -not -path "./vendor/*" | wc -l | xargs echo "JS files:"

  notify:
    name: Notify Results
    runs-on: ubuntu-latest
    needs: [phpcs-check, basic-tests]
    if: always()
    
    steps:
    - name: Notify success
      if: ${{ needs.phpcs-check.result == 'success' && needs.basic-tests.result == 'success' }}
      run: echo "✅ All basic checks passed!"
    
    - name: Notify partial success
      if: ${{ needs.phpcs-check.result != 'success' || needs.basic-tests.result != 'success' }}
      run: echo "⚠️ Some checks had issues, but that's normal for initial setup"